### ISSUE TITLE
[Space] + Z for splitscreen results in tab errors

### ISSUE THREAD

**Issue by JonathanOppenheimer** [theopn/theovim#1] opened 2023-01-16 20:51 UTC
When creating a new split-screen with [Space] + z within Theovim, a new tab called zsh is automatically created. 
<img width="835" alt="Screenshot 2023-01-16 at 3 50 28 PM" src="https://user-images.githubusercontent.com/12973114/212763678-fa47493e-ada8-4d04-bee9-7e0dfb8bf2ed.png">

Attempting to close this tab results in errors: 
<img width="828" alt="Screenshot 2023-01-16 at 3 50 36 PM" src="https://user-images.githubusercontent.com/12973114/212763701-c71b76d2-1b35-4bd6-9e2a-9f47776206ab.png">

It is then impossible to close the automatically created zsh tab without closing the split-screen view. This occurs every single time the split-screen is started.

**Comment by theopn** [comment] 2023-01-16 21:10
Hi Jonathan. It is an intended behavior of BarBar plugin (and other vim "buffer" based "tab" plugin) to create a new "tab" when a different buffer is introduced. Vim traditionally never had a generic "tab" that many people are used to, rather they treated "buffer" as the tab feature. Thus, it is natural for BarBar to create a new tab when a new buffer is introduced.

Simply put, even if you create a new split screen, if it is the same buffer as an existing buffer, it will not create a "tab." Even if the window is within a "tab," if it is a new buffer, it will be reflected in the BarBar plugin.

The error itself is related to NVimTree auto-closing mechanism. I am aware that NVimTree author does not recommend auto-open/auto-closing implementation as it is very error-prone and that my implementation is kind of a workaround.

I am planning on creating a new repository for my Neovim setup. Within that project, I will look into a new tab plugin that behaves more like a "traditional tab" if there is a high demand for it. I will also "fix" the NVimTree auto-closing mechanism, I will likely follow the plugin author's advice and remove the auto-open/auto-closing function as there other more efficient file browsing mechanisms such as Telescope plugin.

Please open the issue in the new project https://github.com/theopn/theovim/ once the repository has been initialized if the issue persists after the first release. Thanks.

**Closed** 2023-01-16 21:11 UTC

**Comment by JonathanOppenheimer** [comment] 2023-01-16 21:20
Hello Theo. I appreciate your timely response and excellent explanation of the cause of this error. I completely understand the cause of this error now and also see why it is a lower-priority issue. Nonetheless, as a representative of one of the largest user groups for Theovim, I can attest that those I represent express a desire for a tabbing feature.

I look forward to the future of Theovim's development with great interest and will certainly be tracking the new repository and its first release. 

Best,
Jonathan

**Comment by theopn** [comment] 2023-01-16 21:22
Lmao thanks Jonathan see you on Wednesday

**Comment by JonathanOppenheimer** [comment] 2023-01-17 03:39
Hello sir. As per above, 
> Please open the issue in the new project https://github.com/theopn/theovim/ once the repository has been initialized if the issue persists after the first release. Thanks.

I have reopened this issue as the described behavior still persists when using Theovim. 

My kindest regards,
Jonathan

**Comment by JonathanOppenheimer** [comment] 2023-01-17 03:39
wait fuck i can't even reopen an issue

**Comment by theopn** [comment] 2023-01-20 15:01
@JonathanOppenheimer the issue has been resolved. The NVimTree will not open on the startup anymore, and the auto close mechanism for NvimTree has been removed, which has been error-prone (https://github.com/nvim-tree/nvim-tree.lua/issues/1005). Thanks for your issue report.
